/** Base UI-shaped AlertDialog entry point. */

export {
  AlertDialog,
  AlertDialog as default,
  AlertDialogRoot as Root,
  AlertDialogTrigger as Trigger,
  DialogPortal as Portal,
  DialogBackdrop as Backdrop,
  DialogPopup as Popup,
  DialogViewport as Viewport,
  DialogTitle as Title,
  DialogDescription as Description,
  DialogClose as Close,
  AlertDialogHandle as Handle,
  createAlertDialogHandle as createHandle,
  AlertDialogRoot,
  AlertDialogTrigger,
  DialogPortal,
  DialogBackdrop,
  DialogPopup,
  DialogViewport,
  DialogTitle,
  DialogDescription,
  DialogClose,
  AlertDialogHandle,
  createAlertDialogHandle,
} from "./dialog.js"

export type {
  AlertDialogRootProps as RootProps,
  AlertDialogRootState as RootState,
  AlertDialogRootChangeEventReason as RootChangeEventReason,
  AlertDialogRootChangeEventDetails as RootChangeEventDetails,
  AlertDialogTriggerProps as TriggerProps,
  AlertDialogTriggerState as TriggerState,
  AlertDialogPortalProps as PortalProps,
  AlertDialogPortalState as PortalState,
  AlertDialogBackdropProps as BackdropProps,
  AlertDialogBackdropState as BackdropState,
  AlertDialogPopupProps as PopupProps,
  AlertDialogPopupState as PopupState,
  AlertDialogViewportProps as ViewportProps,
  AlertDialogViewportState as ViewportState,
  AlertDialogTitleProps as TitleProps,
  AlertDialogTitleState as TitleState,
  AlertDialogDescriptionProps as DescriptionProps,
  AlertDialogDescriptionState as DescriptionState,
  AlertDialogCloseProps as CloseProps,
  AlertDialogCloseState as CloseState,
  AlertDialogRootProps,
  AlertDialogRootState,
  AlertDialogRootChangeEventReason,
  AlertDialogRootChangeEventDetails,
  AlertDialogTriggerProps,
  AlertDialogTriggerState,
  AlertDialogPortalProps,
  AlertDialogPortalState,
  AlertDialogBackdropProps,
  AlertDialogBackdropState,
  AlertDialogPopupProps,
  AlertDialogPopupState,
  AlertDialogViewportProps,
  AlertDialogViewportState,
  AlertDialogTitleProps,
  AlertDialogTitleState,
  AlertDialogDescriptionProps,
  AlertDialogDescriptionState,
  AlertDialogCloseProps,
  AlertDialogCloseState,
  DialogChangeEventDetails,
  DialogInteractionType,
  DialogFocusTarget,
} from "./dialog.js"
