/**
 * `toMatchScreenshot`, wired the way a consumer wires the matcher pack.
 *
 * Goldens here are written into a temporary directory by the test that asserts
 * a missing golden is created, and read back by the ones that follow. Nothing
 * is committed: the point of every assertion below is the matcher's decision,
 * not a particular set of pixels, and a golden generated by the same renderer
 * that reads it keeps the suite honest on any machine.
 */

import { existsSync, mkdtempSync, readFileSync, rmSync } from "node:fs"
import os from "node:os"
import path from "node:path"
import { fileURLToPath } from "node:url"

import React from "react"
import { describe, expect, it } from "vitest"

import { createTestRoot, isNativeTestRendererAvailable, type TestRoot } from "../testing.js"
import { configureScreenshots, gpuixMatchers, type GpuixMatchers } from "../testing-expect.js"
import { decodePng, readPngSize } from "../testing-png.js"
import {
  decideScreenshotOutcome,
  screenshotDiffPaths,
  screenshotPathContext,
  toMatchScreenshot,
  type ScreenshotPathContext,
} from "../testing-screenshot.js"

expect.extend(gpuixMatchers)

declare module "vitest" {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  interface Matchers<T = any> extends GpuixMatchers<T> {}
}

const describeNative = isNativeTestRendererAvailable() ? describe : describe.skip
const here = path.dirname(fileURLToPath(import.meta.url))

const RED = "#ff0000"
const BLUE = "#0000ff"

function Scene({
  color = RED,
  width = 80,
}: {
  color?: string
  width?: number
}): React.ReactElement {
  return (
    <div
      style={{
        display: "flex",
        width: 200,
        height: 120,
        padding: 20,
        backgroundColor: "#102030",
      }}
    >
      <div data-testid="tile" style={{ width, height: 40, backgroundColor: color }} />
    </div>
  )
}

/** Failure messages carry the runner's colours; the assertions are about words. */
function plain(text: string): string {
  return text.replace(/\u001B\[[0-9;]*m/g, "")
}

/** The failure message of an assertion expected to fail, or `""` if it passed. */
async function failure(assertion: Promise<unknown>): Promise<string> {
  return assertion.then(
    () => "",
    (error: Error) => plain(error.message)
  )
}

function scratchDirectory(): string {
  return mkdtempSync(path.join(os.tmpdir(), "gpuix-screenshot-test-"))
}

/** A test root and a temp directory, both released when `body` returns. */
async function withScene(
  body: (screen: TestRoot, directory: string) => Promise<void>
): Promise<void> {
  const directory = scratchDirectory()
  const screen = createTestRoot({ width: 200, height: 120 })
  try {
    await body(screen, directory)
  } finally {
    screen.unmount()
    rmSync(directory, { recursive: true, force: true })
  }
}

describeNative("toMatchScreenshot", () => {
  it("writes a missing golden and fails with vitest's wording", async () => {
    await withScene(async (screen, directory) => {
      screen.render(<Scene />)
      const golden = path.join(directory, "window.png")

      const message = await failure(
        expect(screen).toMatchScreenshot({ resolveScreenshotPath: () => golden })
      )

      expect(message).toContain(
        "No existing reference screenshot found; a new one was created. Review it before running tests again."
      )
      // The layout is vitest's, down to the matcher hint and the coloured path.
      expect(message).toContain("expect(element).toMatchScreenshot()")
      expect(message).toContain("Reference screenshot:")
      expect(message).toContain(golden)
      expect(existsSync(golden)).toBe(true)

      // The window golden is the whole offscreen surface, in device pixels.
      const size = screen.renderer.getWindowSize()
      expect(readPngSize(readFileSync(golden), golden)).toEqual({
        width: size.width * size.scaleFactor,
        height: size.height * size.scaleFactor,
      })
    })
  })

  it("passes on the next run against the golden it wrote", async () => {
    await withScene(async (screen, directory) => {
      screen.render(<Scene />)
      const golden = path.join(directory, "window.png")
      const options = { resolveScreenshotPath: () => golden }

      await expect(expect(screen).toMatchScreenshot(options)).rejects.toThrowError(
        /a new one was created/
      )
      // Same tree, same window: the second run is the assertion the golden exists for.
      await expect(screen).toMatchScreenshot(options)
      // And a re-render of the same tree still matches it.
      screen.render(<Scene />)
      await expect(screen).toMatchScreenshot(options)
    })
  })

  it("writes the reference, actual, and diff artifacts when pixels change", async () => {
    await withScene(async (screen, directory) => {
      const golden = path.join(directory, "tile.png")
      const options = { resolveScreenshotPath: () => golden }
      const artifacts = screenshotDiffPaths(golden)

      screen.render(<Scene />)
      await expect(expect(screen).toMatchScreenshot(options)).rejects.toThrowError(
        /a new one was created/
      )

      screen.render(<Scene color={BLUE} />)
      await expect(expect(screen).toMatchScreenshot(options)).rejects.toThrowError(
        /Screenshot does not match the stored reference\.\n\d+ pixels \(ratio \d+\.\d\d\) differ\./
      )

      expect(existsSync(golden)).toBe(true)
      expect(existsSync(artifacts.actual)).toBe(true)
      expect(existsSync(artifacts.diff)).toBe(true)

      const message = await failure(expect(screen).toMatchScreenshot(options))
      expect(message).toContain(golden)
      expect(message).toContain(artifacts.actual)
      expect(message).toContain(artifacts.diff)

      // The diff is a real image of the same shape, with differing pixels red.
      const diff = decodePng(readFileSync(artifacts.diff), artifacts.diff)
      expect({ width: diff.width, height: diff.height }).toEqual(
        readPngSize(readFileSync(golden), golden)
      )
      let red = 0
      for (let pixel = 0; pixel < diff.width * diff.height; pixel += 1) {
        const at = pixel * 4
        if (diff.data[at] === 255 && diff.data[at + 1] === 0 && diff.data[at + 2] === 0) red += 1
      }
      expect(red).toBeGreaterThan(0)
    })
  })

  it("clips an element capture to its device-pixel box", async () => {
    await withScene(async (screen, directory) => {
      screen.render(<Scene />)
      const golden = path.join(directory, "tile.png")
      const options = { resolveScreenshotPath: () => golden }
      const tile = screen.getByTestId("tile")

      await expect(expect(tile).toMatchScreenshot(options)).rejects.toThrowError(
        /a new one was created/
      )
      await expect(tile).toMatchScreenshot(options)

      const rect = tile.getBoundingClientRect()
      const { scaleFactor } = screen.renderer.getWindowSize()
      const image = decodePng(readFileSync(golden), golden)
      expect({ width: image.width, height: image.height }).toEqual({
        width: rect.width * scaleFactor,
        height: rect.height * scaleFactor,
      })

      // Clipped to the tile, so every pixel is the tile's colour and none is
      // the surrounding background — the crop is at the right offset, not just
      // the right size.
      for (let pixel = 0; pixel < image.width * image.height; pixel += 1) {
        const at = pixel * 4
        expect([image.data[at], image.data[at + 1], image.data[at + 2], image.data[at + 3]]).toEqual(
          [255, 0, 0, 255]
        )
      }

      // The same golden cannot stand in for the window's.
      await expect(expect(screen).toMatchScreenshot(options)).rejects.toThrowError(
        /Expected image dimensions to be/
      )
    })
  })

  it("fails on a dimension mismatch instead of skipping", async () => {
    await withScene(async (screen, directory) => {
      const golden = path.join(directory, "tile.png")
      const options = { resolveScreenshotPath: () => golden }

      screen.render(<Scene />)
      await expect(
        expect(screen.getByTestId("tile")).toMatchScreenshot(options)
      ).rejects.toThrowError(/a new one was created/)

      screen.render(<Scene width={120} />)
      const { scaleFactor } = screen.renderer.getWindowSize()
      await expect(
        expect(screen.getByTestId("tile")).toMatchScreenshot(options)
      ).rejects.toThrowError(
        new RegExp(
          `Expected image dimensions to be ${80 * scaleFactor}×${40 * scaleFactor}px, ` +
            `but received ${120 * scaleFactor}×${40 * scaleFactor}px\\.`
        )
      )
    })
  })

  it("honours resolveScreenshotPath and the context it is handed", async () => {
    await withScene(async (screen, directory) => {
      screen.render(<Scene />)
      const seen: ScreenshotPathContext[] = []

      await expect(
        expect(screen).toMatchScreenshot("custom name.png", {
          resolveScreenshotPath: (context) => {
            seen.push(context)
            return path.join(directory, "nested", `${context.arg}${context.ext}`)
          },
        })
      ).rejects.toThrowError(/a new one was created/)

      expect(existsSync(path.join(directory, "nested", "custom-name.png"))).toBe(true)
      expect(seen).toHaveLength(1)
      expect(seen[0]).toMatchObject({
        arg: "custom-name",
        ext: ".png",
        testFileName: "testing-screenshot.test.tsx",
        screenshotDirectory: "__screenshots__",
        platform: process.platform,
      })
      expect(path.resolve(seen[0]!.root, seen[0]!.testFileDirectory)).toBe(here)
      expect(seen[0]!.testName).toMatch(/toMatchScreenshot-honours-resolveScreenshotPath/)
    })
  })

  it("uses the configureScreenshots default when a call passes no resolveScreenshotPath", async () => {
    await withScene(async (screen, directory) => {
      screen.render(<Scene />)
      const seen: ScreenshotPathContext[] = []
      configureScreenshots({
        resolveScreenshotPath: (context) => {
          seen.push(context)
          return path.join(directory, "configured", `${context.arg}${context.ext}`)
        },
      })

      try {
        const golden = path.join(directory, "configured", "suite-default.png")
        await expect(expect(screen).toMatchScreenshot("suite-default")).rejects.toThrowError(
          /a new one was created/
        )
        expect(existsSync(golden)).toBe(true)
        // The configured resolver is handed the same context a per-call one is.
        expect(seen).toHaveLength(1)
        expect(seen[0]).toMatchObject({
          arg: "suite-default",
          ext: ".png",
          testFileName: "testing-screenshot.test.tsx",
          screenshotDirectory: "__screenshots__",
          platform: process.platform,
        })

        // And the next run passes against the golden it resolved.
        await expect(screen).toMatchScreenshot("suite-default")
      } finally {
        configureScreenshots({})
      }
    })
  })

  it("lets a per-call resolveScreenshotPath override the configured default, as vitest does", async () => {
    await withScene(async (screen, directory) => {
      screen.render(<Scene />)
      const configured = path.join(directory, "configured", "shot.png")
      const perCall = path.join(directory, "per-call", "shot.png")
      configureScreenshots({ resolveScreenshotPath: () => configured })

      try {
        await expect(
          expect(screen).toMatchScreenshot({ resolveScreenshotPath: () => perCall })
        ).rejects.toThrowError(/a new one was created/)

        expect(existsSync(perCall)).toBe(true)
        expect(existsSync(configured)).toBe(false)
      } finally {
        configureScreenshots({})
      }
    })
  })

  it("restores the built-in path when reconfigured with no default", async () => {
    const directory = path.join(here, "__screenshots__", "testing-screenshot.test.tsx")
    const screen = createTestRoot({ width: 200, height: 120 })
    try {
      screen.render(<Scene />)
      configureScreenshots({
        resolveScreenshotPath: () => {
          throw new Error("a cleared default must not be consulted")
        },
      })
      configureScreenshots({})

      await expect(expect(screen).toMatchScreenshot("back-to-default")).rejects.toThrowError(
        /a new one was created/
      )
      expect(existsSync(path.join(directory, "back-to-default.png"))).toBe(true)
    } finally {
      screen.unmount()
      configureScreenshots({})
      rmSync(path.join(here, "__screenshots__"), { recursive: true, force: true })
    }
  })

  it("defaults to __screenshots__ beside the test file, named after the test", async () => {
    const directory = path.join(here, "__screenshots__", "testing-screenshot.test.tsx")
    const screen = createTestRoot({ width: 200, height: 120 })
    try {
      screen.render(<Scene />)
      await expect(expect(screen).toMatchScreenshot()).rejects.toThrowError(
        /a new one was created/
      )

      // The auto-generated name is vitest's: the sanitized test name, then the
      // per-test call counter.
      const golden = path.join(
        directory,
        "toMatchScreenshot-defaults-to-__screenshots__-beside-the-test-file-named-after-the-test-1.png"
      )
      expect(existsSync(golden)).toBe(true)

      await expect(expect(screen).toMatchScreenshot()).rejects.toThrowError(
        /a new one was created/
      )
      expect(
        existsSync(
          path.join(
            directory,
            "toMatchScreenshot-defaults-to-__screenshots__-beside-the-test-file-named-after-the-test-2.png"
          )
        )
      ).toBe(true)
    } finally {
      screen.unmount()
      rmSync(path.join(here, "__screenshots__"), { recursive: true, force: true })
    }
  })

  it("bumps the call counter on named calls, as vitest does", async () => {
    const directory = path.join(here, "__screenshots__", "testing-screenshot.test.tsx")
    const screen = createTestRoot({ width: 200, height: 120 })
    try {
      screen.render(<Scene />)
      await expect(expect(screen).toMatchScreenshot("named-first")).rejects.toThrowError(
        /a new one was created/
      )
      // The named call above consumed slot 1, so the unnamed call is " 2".
      await expect(expect(screen).toMatchScreenshot()).rejects.toThrowError(
        /a new one was created/
      )
      const golden = path.join(
        directory,
        "toMatchScreenshot-bumps-the-call-counter-on-named-calls-as-vitest-does-2.png"
      )
      expect(existsSync(golden)).toBe(true)
    } finally {
      screen.unmount()
      rmSync(path.join(here, "__screenshots__"), { recursive: true, force: true })
    }
  })

  it("overwrites the golden and passes when the runner is updating snapshots", async () => {
    await withScene(async (screen, directory) => {
      const golden = path.join(directory, "tile.png")
      const options = { resolveScreenshotPath: () => golden }

      screen.render(<Scene />)
      await expect(expect(screen).toMatchScreenshot(options)).rejects.toThrowError(
        /a new one was created/
      )
      const before = readFileSync(golden)

      // `--update` reaches a matcher as `snapshotState._updateSnapshot === "all"`,
      // which vitest sets on the expect state before each test. Calling the
      // matcher with that state is the only way to exercise the branch from
      // inside a run that is not itself updating.
      screen.render(<Scene color={BLUE} />)
      const updating = {
        task: { result: { repeatCount: 0 } },
        currentTestName: "updating",
        testPath: path.join(here, "testing-screenshot.test.tsx"),
        snapshotState: { _updateSnapshot: "all" as const },
      }
      const result = await toMatchScreenshot.call(updating, screen, options)
      expect(result.pass).toBe(true)
      expect(readFileSync(golden).equals(before)).toBe(false)

      // And the overwritten golden is the one the blue tree now matches.
      await expect(screen).toMatchScreenshot(options)
    })
  })

  it("refuses a negated assertion and a receiver it cannot capture", async () => {
    await withScene(async (screen, directory) => {
      screen.render(<Scene />)
      const options = { resolveScreenshotPath: () => path.join(directory, "tile.png") }

      await expect(expect(screen).not.toMatchScreenshot(options)).rejects.toThrowError(
        `'toMatchScreenshot' cannot be used with "not"`
      )
      await expect(expect({ nothing: true }).toMatchScreenshot(options)).rejects.toThrowError(
        /toMatchScreenshot expects a render result, a TestRenderer, or a TestElement/
      )
    })
  })
})

describe("toMatchScreenshot decisions", () => {
  const size = { width: 4, height: 4 }
  const comparator = { tolerance: 0, differingPixelBudget: 0, maxChannelDelta: 255 }
  const clean = {
    differingPixelRatio: 0,
    maxChannelDelta: 0,
    maxChannelDeltaOutsideGoldenContour: 0,
    erodedGeometryMismatchRatio: 0,
  }
  const dirty = { ...clean, differingPixelRatio: 0.25, maxChannelDelta: 255 }

  it("writes a new golden outside CI and withholds it inside CI", () => {
    expect(
      decideScreenshotOutcome({
        reference: null,
        actual: size,
        updateSnapshot: "new",
        comparator,
        compare: () => clean,
      })
    ).toMatchObject({
      type: "missing-reference",
      pass: false,
      location: "reference",
      message:
        "No existing reference screenshot found; a new one was created. Review it before running tests again.",
    })

    expect(
      decideScreenshotOutcome({
        reference: null,
        actual: size,
        updateSnapshot: "none",
        comparator,
        compare: () => clean,
      })
    ).toMatchObject({
      type: "missing-reference",
      location: "diffs",
      message: "No existing reference screenshot found.",
    })
  })

  it("lets --update overwrite a missing, differing, or resized golden", () => {
    const update = (input: Partial<Parameters<typeof decideScreenshotOutcome>[0]>) =>
      decideScreenshotOutcome({
        reference: size,
        actual: size,
        updateSnapshot: "all",
        comparator,
        compare: () => dirty,
        ...input,
      })

    expect(update({ reference: null })).toMatchObject({ type: "update-reference", pass: true })
    expect(update({})).toMatchObject({ type: "update-reference", pass: true })
    // vitest lets `--update` past a size change too, rather than failing first.
    expect(update({ actual: { width: 8, height: 4 } })).toMatchObject({
      type: "update-reference",
      pass: true,
    })
  })

  it("fails a size change without comparing pixels", () => {
    let compared = false
    const outcome = decideScreenshotOutcome({
      reference: size,
      actual: { width: 8, height: 4 },
      updateSnapshot: "new",
      comparator,
      compare: () => {
        compared = true
        return clean
      },
    })

    expect(compared).toBe(false)
    expect(outcome).toMatchObject({
      type: "dimension-mismatch",
      pass: false,
      message:
        "Screenshot does not match the stored reference.\n" +
        "Expected image dimensions to be 4×4px, but received 8×4px.",
    })
  })

  it("reports the differing pixel count and the channel ceiling it broke", () => {
    expect(
      decideScreenshotOutcome({
        reference: size,
        actual: size,
        updateSnapshot: "new",
        comparator,
        compare: () => dirty,
      })
    ).toMatchObject({
      type: "mismatch",
      message:
        "Screenshot does not match the stored reference.\n4 pixels (ratio 0.25) differ.",
    })

    expect(
      decideScreenshotOutcome({
        reference: size,
        actual: size,
        updateSnapshot: "new",
        comparator: { tolerance: 2, differingPixelBudget: 1, maxChannelDelta: 16 },
        compare: () => ({ ...clean, differingPixelRatio: 0.5, maxChannelDelta: 40 }),
      })
    ).toMatchObject({
      type: "mismatch",
      message:
        "Screenshot does not match the stored reference.\n" +
        "8 pixels (ratio 0.50) differ. Maximum channel delta 40 exceeds the ceiling 16.",
    })
  })

  it("passes a comparison inside the budget", () => {
    expect(
      decideScreenshotOutcome({
        reference: size,
        actual: size,
        updateSnapshot: "new",
        comparator: { tolerance: 2, differingPixelBudget: 0.5, maxChannelDelta: 16 },
        compare: () => ({ ...clean, differingPixelRatio: 0.25, maxChannelDelta: 10 }),
      })
    ).toMatchObject({ type: "matched", pass: true })
  })

  it("sanitizes a name into a path that cannot leave the screenshot directory", () => {
    const context = (name: string): ScreenshotPathContext =>
      screenshotPathContext({
        name,
        testPath: path.join(here, "testing-screenshot.test.tsx"),
        testName: "suite > case",
      })

    // vitest's own asymmetry, mirrored rather than corrected: a name carrying
    // the extension is reduced to its basename, and one without it keeps its
    // directories — after a `relative('/', ...)` that strips any traversal.
    expect(context("../../secret/Fancy Button!.png").arg).toBe("Fancy-Button")
    expect(context("../../secret/Fancy Button!").arg).toBe("secret/Fancy-Button")
    // An unsupported extension is not one, so it stays part of the name.
    expect(context("shot.jpeg").arg).toBe("shotjpeg")

    const one = context("shot.png")
    expect(one.ext).toBe(".png")
    expect(one.testName).toBe("suite-case")
    expect(one.testFileName).toBe("testing-screenshot.test.tsx")
  })
})
