/* auto-generated by NAPI-RS */
/* eslint-disable */
/** The main GPUI renderer exposed to Node.js. */
export declare class GpuixRenderer {
  constructor(eventCallback?: (((err: Error | null, arg: EventPayload) => any)) | undefined | null)
  /** Initialize GPUI using the native event-loop architecture for this OS. */
  init(options?: WindowOptions | undefined | null): void
  /** Replace the callback used for application-level events such as menu actions. */
  setApplicationEventHandler(eventCallback?: (((arg: EventPayload) => unknown)) | undefined | null): void
  /**
   * Install the renderer-level callback for native window events.
   *
   * Resize dimensions use logical GPUI pixels (points on macOS). Multiply
   * them by `scaleFactor` to obtain device-pixel dimensions.
   */
  setWindowEventHandler(eventCallback?: (((arg: EventPayload) => unknown)) | undefined | null): void
  createElement(id: number, elementType: string): void
  /**
   * Destroy an element and all descendants. Returns array of destroyed IDs
   * so JS can clean up event handlers for the entire subtree.
   */
  destroyElement(id: number): Array<number>
  appendChild(parentId: number, childId: number): void
  removeChild(parentId: number, childId: number): void
  insertBefore(parentId: number, childId: number, beforeId: number): void
  setStyle(id: number, styleJson: string): void
  /**
   * Enable actionable diagnostics for rejected style fields. React enables this
   * by default outside production builds.
   */
  setStrictStyles(enabled: boolean): void
  /**
   * Opt in to loopback and private-network URL image sources.
   * Link-local and cloud-metadata addresses remain blocked.
   */
  setAllowPrivateNetworkImages(enabled: boolean): void
  /** Drain rejected style fields after a commit, once element type and testId are known. */
  drainStyleDiagnostics(): Array<GpuixStyleDiagnostic>
  setText(id: number, content: string): void
  setEventListener(id: number, eventType: string, hasHandler: boolean): void
  /** Set the root element (called from appendChildToContainer). */
  setRoot(id: number): void
  /**
   * Set a custom prop on an element (for non-div/text elements like input, editor, diff).
   * Key is the prop name, value is JSON-encoded.
   */
  setCustomProp(id: number, key: string, valueJson: string): void
  /** Get a custom prop value from an element. Returns JSON string or null. */
  getCustomProp(id: number, key: string): string | null
  /** Signal that a batch of mutations is complete. Triggers re-render. */
  commitMutations(): void
  /**
   * Replace one canvas element's retained display list and repaint without
   * requiring a React commit.
   */
  applyCanvasCommands(id: number, ops: Uint32Array, operands: Float64Array, strings: Array<string>): void
  /**
   * Apply a batch of mutations in a single FFI call.
   *
   * Accepts a JSON array of mutation tuples. Each tuple is an array where
   * the first element is the operation name (string) and remaining elements
   * are the arguments:
   *
   *   ["createElement",    id, "type"]
   *   ["destroyElement",   id]
   *   ["appendChild",      parentId, childId]
   *   ["removeChild",      parentId, childId]
   *   ["insertBefore",     parentId, childId, beforeId]
   *   ["setStyle",         id, { ...style } | "{styleJson}"]
   *   ["setText",          id, "content"]
   *   ["setEventListener", id, "eventType", true|false]
   *   ["setRoot",          id]
   *   ["setCustomProp",      id, "key", value | "{valueJson}"]
   *   ["setCustomPropValue", id, "key", value]
   *
   * Returns accumulated destroyed IDs from all destroyElement ops.
   * Acquires the tree mutex ONCE for the entire batch.
   */
  applyBatch(json: string): Array<number>
  /** Replace the application menu bar. Pass an empty array to remove it. */
  setMenus(menus: Array<MenuSpec>): void
  /** Dispatch a configured menu action through the production GPUI application. */
  simulateMenuAction(id: string): void
  /** Gracefully terminate the native application through GPUI's platform abstraction. */
  quit(): void
  /**
   * Pump the native event loop. Returns false after the last window closes.
   * A pending display-link token is dispatched immediately before this pump.
   */
  tick(): boolean
  /**
   * Pump idle platform work without dispatching a pending frame token.
   * This keeps input and application lifecycle events responsive between frames.
   */
  tickIdle(): boolean
  isInitialized(): boolean
  /**
   * Stable platform and renderer feature read. Keep individual methods for
   * backwards compatibility; new callers should branch on this object.
   */
  capabilities(): RendererCapabilities
  /** Whether JavaScript must drive the native event loop with tick(). */
  requiresTick(): boolean
  /**
   * Registers a coalesced display-link frame request callback when supported.
   * Returns false when this renderer must be timer-driven instead.
   */
  setFrameRequestHandler(callback?: ((() => unknown)) | undefined | null): boolean
  /**
   * Queue one callback on GPUI's next display-paced frame. `on_next_frame`
   * creates frame demand without dirtying the window, so an otherwise idle
   * callback does not force a draw.
   */
  requestFrame(callback: (timestamp: number) => void): void
  /** Whether this native window is active and receiving key events. */
  isActive(): boolean
  /** Bring the native window and application to the foreground. */
  activateWindow(): void
  getWindowSize(): WindowSize
  getWindowInsets(): WindowInsets
  /** `"hidden"` | `"minimal"` | `"full"`. Paints into the scene after layout. */
  setDebugFrameOverlay(mode: string): string
  /** Hidden → minimal → full → hidden. */
  cycleDebugFrameOverlay(): string
  getDebugFrameOverlay(): string
  /** Clears the last 1000 draw samples. Frame count stays. */
  resetDebugFrameOverlayStats(): void
  /** Same numbers as the on-screen overlay: current, p90, p99, max, frames. */
  getDebugFrameOverlayStats(): DebugFrameOverlayStats
  setWindowTitle(title: string): void
  focusElement(elementId: number): void
  /** Route the active pressed-pointer sequence to this retained element. */
  setPointerCapture(elementId: number): void
  /** Release capture only when this retained element currently owns it. */
  releasePointerCapture(elementId: number): void
  blur(): void
  /** The current text selection joined in document order, or null. */
  getSelectedText(): string | null
  /** Drop the current selection and request a repaint. */
  clearSelection(): void
  /**
   * Set the scroll offset of a scrollable element.
   * x and y are negative pixel values (scroll down = more negative y).
   */
  scrollTo(elementId: number, x: number, y: number): void
  /** Scroll a child into view by its index in the children list. */
  scrollToItem(elementId: number, index: number): void
  /** Starts a macOS profiler capture at GPUI's post-platform-submit present boundary. */
  startPresentTimingCapture(): void
  /** Ends the capture and returns ordered millisecond offsets for submitted frames. */
  takePresentTimestamps(): Array<number>
  /**
   * Get the current scroll offset of a scrollable element.
   * Returns [x, y] or null if the element has no scroll handle.
   */
  getScrollOffset(elementId: number): Array<number> | null
  getAutomationTree(): string
  getElementBounds(id: number): Array<number> | null
  getAllText(): Array<string>
  getPaintedText(): Array<string>
  /**
   * Every highlight wash painted in the last frame, in paint order.
   *
   * A quad is invisible to `getPaintedText()`, so this is the only way to
   * assert on `highlight` without a screenshot.
   */
  getPaintedHighlights(): Array<HighlightMatch>
  /** Simulate space-separated keystrokes through the focused element's input pipeline. */
  simulateKeystrokes(keystrokes: string): void
  simulateKeyDown(keystroke: string, isHeld?: boolean | undefined | null): void
  simulateKeyUp(keystroke: string): void
  /** `modifiers` uses the `press()` syntax: "cmd", "cmd-shift", "alt". */
  simulateClick(x: number, y: number, button?: number | undefined | null, modifiers?: string | undefined | null): void
  simulateMouseDown(x: number, y: number, button?: number | undefined | null, modifiers?: string | undefined | null): void
  simulateMouseUp(x: number, y: number, button?: number | undefined | null, modifiers?: string | undefined | null): void
  simulateMouseMove(x: number, y: number, pressedButton?: number | undefined | null, modifiers?: string | undefined | null): void
  /**
   * Dispatch a wheel event through the same GPUI hit test the trackpad uses.
   * The options preserve gesture phase, line/pixel units, and modifiers.
   */
  simulateScrollWheel(x: number, y: number, deltaX: number, deltaY: number, options?: ScrollWheelOptions | undefined | null): void
  /** Draws completed inline while live automation dispatched scroll input. */
  getSynchronousScrollDrawCount(): number
  clockPause(): number
  clockSet(nowMs: number): number
  clockFastForward(deltaMs: number): number
  clockResume(): number
  captureScreenshot(path: string): void
  /**
   * Test seam for a native frame callback that arrives after tickIdle's
   * outstanding-work precheck. The callback is queued from a background
   * thread while the embedded AppKit pump owns the JavaScript thread.
   */
  testIdlePumpFrameRequestRace(callback: FrameRequestCallback): boolean
}

/**
 * GPU-backed GPUI test renderer. Uses VisualTestAppContext with the native
 * Metal or DirectX renderer and TestDispatcher for deterministic scheduling.
 * Same GpuixView and rendering pipeline as production.
 *
 * Usage from JS:
 *   const r = new TestGpuixRenderer()
 *   r.createElement(1, "div")
 *   r.setRoot(1)
 *   r.commitMutations()
 *   r.flush()                  // triggers GpuixView::render() on the GPU
 *   r.simulateClick(50, 50)    // dispatches through GPUI hit testing
 *   const events = r.drainEvents()
 *   r.captureScreenshot("/tmp/test.png")  // saves rendered UI as PNG
 */
export declare class TestGpuixRenderer {
  constructor(width?: number | undefined | null, height?: number | undefined | null)
  /**
   * Dispose this renderer's offscreen window and GPUI application context.
   * Further interaction attempts fail instead of being routed to another root.
   */
  dispose(): void
  /**
   * The same capability contract as a live renderer, scoped to this
   * offscreen GPU-backed window.
   */
  capabilities(): RendererCapabilities
  createElement(id: number, elementType: string): void
  /**
   * Destroy an element and all descendants. Returns destroyed IDs
   * so JS can clean up event handlers.
   */
  destroyElement(id: number): Array<number>
  appendChild(parentId: number, childId: number): void
  removeChild(parentId: number, childId: number): void
  insertBefore(parentId: number, childId: number, beforeId: number): void
  setStyle(id: number, styleJson: string): void
  setStrictStyles(enabled: boolean): void
  /**
   * Opt in to loopback and private-network URL image sources for local tests.
   * Link-local and cloud-metadata addresses remain blocked.
   */
  setAllowPrivateNetworkImages(enabled: boolean): void
  drainStyleDiagnostics(): Array<GpuixStyleDiagnostic>
  setText(id: number, content: string): void
  setEventListener(id: number, eventType: string, hasHandler: boolean): void
  /** Set the root element (called from appendChildToContainer). */
  setRoot(id: number): void
  /** Set a custom prop on an element (for non-div/text elements like input, editor, diff). */
  setCustomProp(id: number, key: string, valueJson: string): void
  /** Get a custom prop value from an element. */
  getCustomProp(id: number, key: string): string | null
  /**
   * Signal that a batch of mutations is complete.
   * In tests, this is a no-op — flush() handles the actual re-render.
   */
  commitMutations(): void
  /**
   * Replace one canvas element's retained display list and notify the
   * offscreen view without requiring a React commit.
   */
  applyCanvasCommands(id: number, ops: Uint32Array, operands: Float64Array, strings: Array<string>): void
  /**
   * Apply a batch of mutations in a single FFI call.
   * Same format as GpuixRenderer::apply_batch (string op names).
   * Returns accumulated destroyed IDs from all destroyElement ops.
   */
  applyBatch(json: string): Array<number>
  /** Replace the application menu using the production conversion and GPUI APIs. */
  setMenus(menus: Array<MenuSpec>): void
  /** Dispatch a configured application action through GPUI's global action pipeline. */
  simulateMenuAction(id: string): void
  /** Whether GPUI reports a currently installed application menu bar. */
  hasMainMenu(): boolean
  /**
   * Notify the view entity and run GPUI until parked.
   * This triggers GpuixView::render() → build_element() → GPUI layout.
   * Must be called after mutations and before simulating events (GPUI's
   * hit testing requires elements to be laid out).
   */
  flush(): void
  /**
   * Queue one callback for the next manually advanced GPUI frame without
   * dirtying or synchronously drawing the offscreen window.
   */
  requestFrame(callback: (timestamp: number) => void): void
  /**
   * Advance GPUI's async executor clock so tests can deterministically fire
   * timers such as bounded image retry/revalidation deadlines. When the
   * renderer animation clock is paused, advance that clock by the same
   * amount and render the resulting transition frame as well.
   */
  advanceAsyncClock(deltaMs: number): void
  /** Override GPUI's reduced-motion policy for deterministic tests. */
  setReducedMotion(enabled: boolean): void
  /**
   * Number of retained style-transition tracks. Exposed only by the
   * offscreen renderer so lifecycle tests can prove unmounted tracks leave.
   */
  getStyleTransitionCount(): number
  /**
   * Number of GPUI frame requests emitted by active style transitions since
   * this offscreen renderer was created. Imperative motion is not counted.
   */
  getStyleTransitionFrameRequestCount(): number
  getWindowSize(): WindowSize
  /** Simulate a native window resize through GPUI's bounds observer. */
  simulateResize(width: number, height: number): void
  /**
   * Simulate a click at the given window coordinates.
   * Dispatches MouseDown + MouseUp through GPUI's input pipeline,
   * which triggers the same event handlers as production.
   * IMPORTANT: Call flush() before this — hit testing requires laid-out elements.
   * `modifiers` uses the `press()` syntax: "cmd", "cmd-shift", "alt".
   */
  simulateClick(x: number, y: number, button?: number | undefined | null, modifiers?: string | undefined | null): void
  /**
   * Simulate key strokes through GPUI's input pipeline.
   * Format: space-separated keys, e.g. "a", "enter", "cmd-shift-p".
   * The focused element receives keyDown/keyUp events.
   */
  simulateKeystrokes(keystrokes: string): void
  /**
   * Simulate a single key down event through GPUI's input pipeline.
   * Format: modifier-key string, e.g. "a", "enter", "cmd-s".
   * Unlike simulate_keystrokes, this dispatches ONLY a KeyDownEvent —
   * no automatic KeyUpEvent follows. Use with simulate_key_up for
   * fine-grained key event testing.
   */
  simulateKeyDown(keystroke: string, isHeld?: boolean | undefined | null): void
  /**
   * Simulate a single key up event through GPUI's input pipeline.
   * Format: modifier-key string, e.g. "a", "enter", "cmd-s".
   * Pairs with simulate_key_down for fine-grained key event testing.
   */
  simulateKeyUp(keystroke: string): void
  /**
   * Simulate a mouse move to the given coordinates.
   * pressed_button: optional mouse button held during move (0=left, 1=middle, 2=right).
   * Used to simulate drag events.
   */
  simulateMouseMove(x: number, y: number, pressedButton?: number | undefined | null, modifiers?: string | undefined | null): void
  /**
   * Focus an element by its numeric ID.
   * The element must have a FocusHandle (created by sync_focus_handles when
   * the element has keyDown, keyUp, focus, or blur listeners).
   * Call flush() before this so the element tree and focus handles exist.
   */
  focusElement(id: number): void
  setPointerCapture(id: number): void
  releasePointerCapture(id: number): void
  /** Simulate a platform window activation change through the production observer path. */
  simulateWindowActivation(active: boolean): void
  /** Simulate the platform deactivating the test window. */
  simulateWindowDeactivation(): void
  /** Whether the offscreen native window is active and receiving key events. */
  isActive(): boolean
  /** An offscreen test window cannot request foreground activation. */
  activateWindow(): void
  /**
   * Simulate a mouse down event at the given window coordinates.
   * Button: 0=left, 1=middle, 2=right. Defaults to left (0).
   */
  simulateMouseDown(x: number, y: number, button?: number | undefined | null, modifiers?: string | undefined | null): void
  /**
   * Simulate a mouse up event at the given window coordinates.
   * Button: 0=left, 1=middle, 2=right. Defaults to left (0).
   */
  simulateMouseUp(x: number, y: number, button?: number | undefined | null, modifiers?: string | undefined | null): void
  /**
   * Simulate a scroll wheel event at the given position.
   * delta_x and delta_y default to pixels (negative = scroll up/left).
   */
  simulateScrollWheel(x: number, y: number, deltaX: number, deltaY: number, options?: ScrollWheelOptions | undefined | null): void
  /** The current text selection joined in document order, or null. */
  getSelectedText(): string | null
  /** Drop the current selection. */
  clearSelection(): void
  /**
   * Syntax-cache counters as `[hits, misses, documents]`.
   *
   * GPUIX rebuilds its whole element tree every frame, so a `<code>` block
   * that misses the cache reparses at frame rate. A test can watch the hit
   * count to catch that regression before a profiler does.
   */
  getSyntaxCacheStats(): Array<number>
  /**
   * Every string painted in the last frame, in paint order.
   *
   * `getAllText()` only sees `<text>` nodes in the retained tree. Native
   * elements such as `<code>` and `<diff>` draw their text inside gpui, so
   * this is the only way to assert on what they actually rendered.
   */
  getPaintedText(): Array<string>
  /**
   * Every highlight wash painted in the last frame, in paint order.
   *
   * A quad is invisible to `getPaintedText()`, so this is the only way to
   * assert on `highlight` without a screenshot. Each entry carries its rects,
   * so a soft-wrapped match is provably two boxes.
   */
  getPaintedHighlights(): Array<HighlightMatch>
  /**
   * Drag-select from one point to another: mouse down, move, up.
   *
   * A single helper rather than three calls because the listeners that drive
   * selection are registered during **paint**, so a flush must sit between
   * the down and the move. Getting that order wrong silently selects nothing,
   * which is a miserable thing to debug from JS.
   */
  dragSelect(x1: number, y1: number, x2: number, y2: number): void
  /**
   * Set the scroll offset of a scrollable element.
   * x and y are negative pixel values (scroll down = more negative y).
   * Call flush() after to apply the offset and re-render.
   */
  scrollTo(elementId: number, x: number, y: number): void
  /**
   * Scroll a child into view by its index in the children list.
   * Call flush() after to apply and re-render.
   */
  scrollToItem(elementId: number, index: number): void
  /** `"hidden"` | `"minimal"` | `"full"`. */
  setDebugFrameOverlay(mode: string): string
  /** Hidden → minimal → full → hidden. */
  cycleDebugFrameOverlay(): string
  getDebugFrameOverlay(): string
  /** Clears the last 1000 draw samples. Frame count stays. */
  resetDebugFrameOverlayStats(): void
  /** Same numbers as the on-screen overlay: current, p90, p99, max, frames. */
  getDebugFrameOverlayStats(): DebugFrameOverlayStats
  /**
   * Get the current scroll offset of a scrollable element.
   * Returns [x, y] or null if the element has no scroll handle.
   */
  getScrollOffset(elementId: number): Array<number> | null
  /**
   * Capture a screenshot of the current rendered state and save as PNG.
   * Supported on macOS through Metal and Windows through DirectX.
   */
  captureScreenshot(path: string): void
  /**
   * Compare two PNG screenshots using an absolute tolerance for each RGBA channel.
   *
   * Future D1/fillText scenes will not be deterministic across browser and native due to
   * font selection, shaping, and antialiasing. Transparent scenes will require an explicit
   * straight-alpha comparison policy; the current committed scenes intentionally remain opaque.
   */
  compareImages(pathA: string, pathB: string, tolerance: number): ImageComparisonResult
  /**
   * Return and clear all collected events since the last drain.
   * Events are collected synchronously — no event loop queuing.
   */
  drainEvents(): Array<EventPayload>
  /** Get all text content in the tree (depth-first order). */
  getAllText(): Array<string>
  /** Find element IDs matching the given type (e.g. "div", "text"). */
  findByType(elementType: string): Array<number>
  /** Resolve an author-defined `id` attribute to the renderer element ID. */
  findByElementId(authorId: string): number | null
  /** Resolve a standard `data-testid` attribute to the renderer element ID. */
  findByDataTestId(dataTestId: string): number | null
  /** Check if an element has a specific event listener. */
  hasEventListener(id: number, eventType: string): boolean
  /** Get the text content of an element. */
  getText(id: number): string | null
  /** Get the full tree as JSON for snapshot testing. */
  getTreeJson(): string
  /**
   * Return the declared descriptor with currently applied state refinements
   * overlaid in the same order GPUI resolves them for painting.
   */
  getResolvedStyle(id: number): string | null
  /**
   * Return the current async image load state for a live `<img>` element.
   * This is test-only state; production images keep their loading fallback.
   */
  getImageLoadState(id: number): string | null
  /** Tree JSON with last-paint bounds. Used by the automation locators. */
  getAutomationTree(): string
  /** Last painted bounds for an element, or null if it was not painted. */
  getElementBounds(id: number): Array<number> | null
  clockPause(): number
  clockSet(nowMs: number): number
  clockFastForward(deltaMs: number): number
  clockResume(): number
  /** Get the root element ID, or null if no root is set. */
  getRootId(): number | null
}

export interface AutomationCapabilities {
  click: boolean
  hover: boolean
  drag: boolean
  scrollWheel: boolean
  /** `native` injects through GPUI; `browser` uses the browser IME mirror. */
  keyboard: "native" | "browser"
  screenshot: boolean
  /** Screenshot file formats currently accepted by `captureScreenshot()`. */
  screenshotFormats: Array<"png">
  clock: boolean
  tree: boolean
}

/** Recorded draw times from the debug frame overlay. */
export interface DebugFrameOverlayStats {
  currentMs?: number
  p90Ms?: number
  p99Ms?: number
  maxMs?: number
  frames: number
  samples: number
}

export interface EdgeInsets {
  top: number
  right: number
  bottom: number
  left: number
}

export interface EventModifiers {
  shift: boolean
  ctrl: boolean
  alt: boolean
  cmd: boolean
}

/** Event payload sent back to JS when a user interacts with an element. */
export interface EventPayload {
  /** Numeric element ID (matches the ID assigned in JS via createElement). */
  elementId: number
  /**
   * Event type string — matches the key used in EVENT_PROPS on the JS side.
   * e.g. "click", "mouseDown", "mouseEnter", "keyDown", "scroll", etc.
   */
  eventType: string
  /** Logical GPUI window width. Populated for `windowResize`. */
  width?: number
  /** Logical GPUI window height. Populated for `windowResize`. */
  height?: number
  /** Device pixels per logical GPUI pixel. Populated for `windowResize`. */
  scaleFactor?: number
  /** Whether the native window is active. Populated for `windowActivation`. */
  isActive?: boolean
  /** Mouse X position in window coordinates (pixels). */
  x?: number
  /** Mouse Y position in window coordinates (pixels). */
  y?: number
  /**
   * Which mouse button: 0=left, 1=middle, 2=right.
   * Populated for: mouseDown, mouseUp, click, mouseDownOutside, contextMenu.
   */
  button?: number
  /**
   * Number of consecutive clicks (1=single, 2=double, 3=triple).
   * Populated for: mouseDown, mouseUp, click.
   */
  clickCount?: number
  /**
   * Whether this is a right-click (convenience for click events).
   * true when button==2 or ClickEvent::is_right_click().
   */
  isRightClick?: boolean
  /**
   * Physical input that produced a click: "mouse", "keyboard", or "touch".
   * Populated for: click.
   */
  inputSource?: string
  /**
   * Which mouse button is currently held during a mouseMove.
   * Same encoding as `button`: 0=left, 1=middle, 2=right.
   * Populated for: mouseMove.
   */
  pressedButton?: number
  /**
   * Key name, e.g. "a", "enter", "escape", "down", "left", "f1".
   * Populated for: keyDown, keyUp.
   */
  key?: string
  /**
   * The character produced by the key press (e.g. "ß" for option-s).
   * May differ from `key` when modifiers are active.
   * Populated for: keyDown, keyUp.
   */
  keyChar?: string
  /**
   * Whether this is a key-repeat event (key held down).
   * Populated for: keyDown.
   */
  isHeld?: boolean
  /**
   * Scroll delta on the X axis (pixels or lines, see `precise`).
   * Populated for: scroll.
   */
  deltaX?: number
  /**
   * Scroll delta on the Y axis (pixels or lines, see `precise`).
   * Populated for: scroll.
   */
  deltaY?: number
  /**
   * true = pixel-precise (trackpad), false = line-based (mouse wheel).
   * Populated for: scroll.
   */
  precise?: boolean
  /**
   * Touch phase for scroll: "started", "moved", "ended".
   * Populated for: scroll (trackpad gestures).
   */
  touchPhase?: string
  /**
   * true = mouse entered element, false = mouse left element.
   * Populated for: mouseEnter, mouseLeave.
   */
  hovered?: boolean
  /**
   * Element-defined string payload.
   * Populated for: `<diff>` toggleFile (the file path), showMore (the
   * hidden line count), and lineClick (the line text); `<markdown>`
   * linkClick (the URL).
   */
  value?: string
  /** Line number on the pre-change side. Populated for: `<diff>` lineClick. */
  oldLine?: number
  /** Line number on the post-change side. Populated for: `<diff>` lineClick. */
  newLine?: number
  /** First visible logical index. Populated for: `<virtual-list>` visibleRange. */
  startIndex?: number
  /** Exclusive end of the visible logical range. Populated for: visibleRange. */
  endIndex?: number
  /**
   * Matches found by this element's `highlight` prop. Counted once per match
   * even when it is split across several painted runs, and it counts every
   * retained match, not only the ones currently on screen.
   * Populated for: highlight.
   */
  matchCount?: number
  modifiers?: EventModifiers
}

export interface FrameClockCapabilities {
  /** The source currently driving frame work for this renderer. */
  kind: "display-link" | "timer" | "raf" | "manual"
  requiresTick: boolean
  /**
   * Whether `setFrameRequestHandler()` can switch this renderer to an
   * external frame source.
   */
  externalFrame: boolean
}

export interface GpuixStyleDiagnostic {
  message: string
  elementId: number
  elementType: string
  authorId?: string
  dataTestId?: string
  testId?: string
  property: string
  value: string
}

/**
 * One highlight wash painted in the last frame, with the boxes it drew.
 *
 * The rects matter: a quad never lands in `getPaintedText()`, and a match that
 * soft-wraps must produce one box per visual row. Without the geometry the only
 * way to assert either is a screenshot.
 */
export interface HighlightMatch {
  /** Numeric id of the element that painted the run. */
  elementId: number
  /** Index of the run within that element. 0 for a plain `<text>`. */
  sub: number
  /** The full string of the run, so `text.slice(start, end)` is the match. */
  text: string
  /** UTF-16 code-unit offsets into `text`, the units JS strings use. */
  start: number
  end: number
  active: boolean
  rects: Array<HighlightRect>
}

export interface HighlightRect {
  x: number
  y: number
  width: number
  height: number
}

export interface ImageCapabilities {
  /** `setAllowPrivateNetworkImages()` is available. */
  privateNetwork: boolean
}

export interface ImageComparisonResult {
  differingPixelRatio: number
  maxChannelDelta: number
}

/**
 * A cross-platform application menu item.
 *
 * `kind` is `"action"`, `"separator"`, `"submenu"`, or `"system"`.
 * Action items require `label` and `id`; use `role: "quit"` for the
 * platform quit action. System items currently support `systemMenu:
 * "services"`.
 */
export interface MenuItemSpec {
  kind: string
  label?: string
  id?: string
  items?: Array<MenuItemSpec>
  disabled?: boolean
  checked?: boolean
  keyEquivalent?: string
  role?: string
  systemMenu?: string
  osAction?: string
}

/** One top-level application menu. */
export interface MenuSpec {
  name: string
  items: Array<MenuItemSpec>
  disabled?: boolean
}

/**
 * Features offered by one renderer instance on its current platform.
 *
 * Each `true` capability corresponds to a callable renderer method. Calls
 * outside the advertised surface reject with `UnsupportedCapabilityError`.
 */
export interface RendererCapabilities {
  platform: "macos" | "windows" | "linux" | "freebsd" | "browser" | "unknown"
  frameClock: FrameClockCapabilities
  window: WindowCapabilities
  images: ImageCapabilities
  automation: AutomationCapabilities
}

export interface ScrollWheelModifiers {
  shift?: boolean
  ctrl?: boolean
  alt?: boolean
  cmd?: boolean
  function?: boolean
}

/**
 * The platform-level fields GPUI records for a scroll-wheel input.
 *
 * Keep this at the automation boundary so the test and live renderers inject
 * identical events.
 */
export interface ScrollWheelOptions {
  phase?: "started" | "moved" | "ended" | "cancelled"
  momentumPhase?: "started" | "moved" | "ended" | "cancelled"
  deltaUnit?: "pixels" | "lines"
  modifiers?: ScrollWheelModifiers
}

export interface WindowCapabilities {
  /** `isActive()` is available for this renderer/window. */
  activation: boolean
  /** `activateWindow()` can request foreground activation. */
  activate: boolean
  /** Native/browser resize notifications are available. */
  resize: boolean
  /** GPUIX currently owns one window per renderer process. */
  multiple: boolean
}

export interface WindowInsets {
  safeArea: EdgeInsets
  ime: EdgeInsets
  effective: EdgeInsets
}

export interface WindowOptions {
  title?: string
  /** The name used for the default application menu. Defaults to `title`. */
  appName?: string
  /** Application menus. Omit for the platform default; pass `[]` to opt out. */
  menus?: Array<MenuSpec>
  width?: number
  height?: number
  minWidth?: number
  minHeight?: number
  resizable?: boolean
  fullscreen?: boolean
  /** Plain alpha transparency. Prefer `window_background` when you need blur. */
  transparent?: boolean
  /** Hide the native titlebar so the app can draw chrome under the traffic lights. */
  titlebarTransparent?: boolean
  /**
   * `"opaque"` | `"transparent"` | `"blurred"`. `transparent: true` is the
   * same as `"transparent"` when this is unset.
   */
  windowBackground?: string
  trafficLightX?: number
  trafficLightY?: number
  /** Force GPUI's reduced-motion policy for this application. */
  reducedMotion?: boolean
  /**
   * Allow URL-backed images to connect to loopback and private networks.
   * Link-local and cloud-metadata ranges remain blocked.
   */
  allowPrivateNetworkImages?: boolean
}

export interface WindowSize {
  width: number
  height: number
  scaleFactor: number
}
