name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MACOSX_DEPLOYMENT_TARGET: "10.13"

permissions: {}

jobs:
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - name: Clone repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup bun
        uses: ./.github/actions/bun

      - name: Build
        run: bun run build --exclude packages/native

      - name: Typecheck
        run: bun run typecheck

  build:
    name: Build (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - name: Clone repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          submodules: recursive

      - name: Setup bun
        uses: ./.github/actions/bun

      - name: Setup rust
        uses: ./.github/actions/rust

      - name: Setup macos
        if: runner.os == 'macOS'
        uses: ./.github/actions/macos

      - name: Setup linux
        if: runner.os == 'Linux'
        uses: ./.github/actions/linux

      - name: Build
        run: bun run build

  test:
    name: Test (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    permissions:
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          submodules: recursive

      - name: Setup bun
        uses: ./.github/actions/bun

      - name: Setup rust
        uses: ./.github/actions/rust

      - name: Setup macos
        if: runner.os == 'macOS'
        uses: ./.github/actions/macos

      - name: Setup linux
        if: runner.os == 'Linux'
        uses: ./.github/actions/linux

      - name: Test plugins package
        run: bun run test
